/*
* To change this license header, choose License Headers in Project Properties.
* To change this template file, choose Tools | Templates
* and open the template in the editor.
*/
package CapaPresentacion;

import CapaNegocios.NEmpleado;
import CapaNegocios.NProveedor;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jfpal
 */
public class EmpleadoScn extends javax.swing.JFrame {
    
    /**
     * Creates new form EmpleadoScn
     */
    public EmpleadoScn() {
        initComponents();
        this.IngBtn.setVisible(false);
        this.SaveBtn.setVisible(false);
        this.ElimBtn.setVisible(false);
        this.EditBtn.setVisible(false);
        this.CancelBtn.setVisible(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        empTbl = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ciTxt = new javax.swing.JTextField();
        nomTxt = new javax.swing.JTextField();
        apeTxt = new javax.swing.JTextField();
        fnacTxt = new javax.swing.JTextField();
        dirTxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        crgCombo = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        horCombo = new javax.swing.JComboBox();
        CancelBtn = new javax.swing.JButton();
        ElimBtn = new javax.swing.JButton();
        EditBtn = new javax.swing.JButton();
        SaveBtn = new javax.swing.JButton();
        IngBtn = new javax.swing.JButton();
        CrearBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("EMPLEADOS");

        empTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "idP", "Nombres", "Apellidos", "Direccion", "Edad", "Cargo", "Horario"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        empTbl.setEnabled(false);
        jScrollPane1.setViewportView(empTbl);
        if (empTbl.getColumnModel().getColumnCount() > 0) {
            empTbl.getColumnModel().getColumn(0).setMinWidth(0);
            empTbl.getColumnModel().getColumn(0).setPreferredWidth(0);
            empTbl.getColumnModel().getColumn(0).setMaxWidth(0);
            empTbl.getColumnModel().getColumn(1).setResizable(false);
            empTbl.getColumnModel().getColumn(2).setResizable(false);
            empTbl.getColumnModel().getColumn(3).setResizable(false);
            empTbl.getColumnModel().getColumn(4).setResizable(false);
            empTbl.getColumnModel().getColumn(5).setResizable(false);
            empTbl.getColumnModel().getColumn(6).setResizable(false);
        }

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("CI:");
        jLabel2.setBorder(null);
        jLabel2.setDoubleBuffered(true);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Nombre:");
        jLabel3.setBorder(null);
        jLabel3.setDoubleBuffered(true);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Apellido:");
        jLabel4.setBorder(null);
        jLabel4.setDoubleBuffered(true);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Direccion:");
        jLabel5.setBorder(null);
        jLabel5.setDoubleBuffered(true);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Fecha de Nacimiento:");
        jLabel6.setBorder(null);
        jLabel6.setDoubleBuffered(true);

        ciTxt.setEnabled(false);
        ciTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ciTxtActionPerformed(evt);
            }
        });

        nomTxt.setEnabled(false);
        nomTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomTxtActionPerformed(evt);
            }
        });

        apeTxt.setEnabled(false);
        apeTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apeTxtActionPerformed(evt);
            }
        });

        fnacTxt.setEnabled(false);
        fnacTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnacTxtActionPerformed(evt);
            }
        });

        dirTxt.setEnabled(false);
        dirTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dirTxtActionPerformed(evt);
            }
        });

        jLabel7.setText("Cargo:");

        crgCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "<Editar>" }));
        crgCombo.setEnabled(false);
        crgCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crgComboActionPerformed(evt);
            }
        });

        jLabel8.setText("Horario:");

        horCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "<Editar>" }));
        horCombo.setEnabled(false);
        horCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                horComboActionPerformed(evt);
            }
        });

        CancelBtn.setText("CANCELAR");
        CancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelBtnActionPerformed(evt);
            }
        });

        ElimBtn.setText("ELIMINAR");
        ElimBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ElimBtnActionPerformed(evt);
            }
        });

        EditBtn.setText("EDITAR");
        EditBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditBtnActionPerformed(evt);
            }
        });

        SaveBtn.setText("GUARDAR");
        SaveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveBtnActionPerformed(evt);
            }
        });

        IngBtn.setText("INGRESAR");
        IngBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngBtnActionPerformed(evt);
            }
        });

        CrearBtn.setText("CREAR");
        CrearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nomTxt)
                                    .addComponent(ciTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(apeTxt)
                                    .addComponent(crgCombo, 0, 191, Short.MAX_VALUE)
                                    .addComponent(horCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(122, 122, 122)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(EditBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ElimBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(CrearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(IngBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(SaveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fnacTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dirTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 813, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(383, 383, 383)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(ciTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(nomTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(dirTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                                .addComponent(fnacTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(apeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(crgCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(horCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CrearBtn)
                            .addComponent(IngBtn))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EditBtn)
                            .addComponent(SaveBtn))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ElimBtn)
                            .addComponent(CancelBtn))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void ciTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ciTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ciTxtActionPerformed
    
    private void nomTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomTxtActionPerformed
    
    private void apeTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apeTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apeTxtActionPerformed
    
    private void fnacTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnacTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnacTxtActionPerformed
    
    private void dirTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dirTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dirTxtActionPerformed
    
    private void CancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelBtnActionPerformed
        // TODO add your handling code here:
        boolean flag=true;
        if(this.IngBtn.isVisible()&&!this.CrearBtn.isVisible()&&!this.EditBtn.isVisible()&&!this.ElimBtn.isVisible()){
            this.CrearBtn.setVisible(true);
            this.IngBtn.setVisible(false);
            this.CancelBtn.setVisible(false);
            this.nomTxt.enable(false);
            this.apeTxt.enable(false);
            this.ciTxt.enable(false);
            this.dirTxt.enable(false);
            this.fnacTxt.enable(false);
            this.crgCombo.enable(false);
            this.horCombo.enable(false);
        }
        if(!this.EditBtn.isVisible()&&this.SaveBtn.isVisible()&&!this.ElimBtn.isVisible()){
            this.EditBtn.setVisible(true);
            this.ElimBtn.setVisible(true);
            
            this.nomTxt.enable(false);
            this.apeTxt.enable(false);
            this.ciTxt.enable(false);
            this.dirTxt.enable(false);
            this.fnacTxt.enable(false);
            this.crgCombo.enable(false);
            this.horCombo.enable(false);
            this.SaveBtn.setVisible(false);
            flag=false;
        }
        if(this.EditBtn.isVisible()&&this.ElimBtn.isVisible()&&!this.SaveBtn.isVisible()&&flag){
            this.EditBtn.setVisible(false);
            this.ElimBtn.setVisible(false);
            this.CrearBtn.setVisible(true);
            this.CancelBtn.setVisible(false);
            this.nomTxt.setText("");
            this.apeTxt.setText("");
            this.ciTxt.setText("");
            this.dirTxt.setText("");
            this.fnacTxt.setText("");
            this.crgCombo.setSelectedIndex(0);
            this.horCombo.setSelectedIndex(0);
        }
    }//GEN-LAST:event_CancelBtnActionPerformed
    
    private void ElimBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ElimBtnActionPerformed
        //DeleteData();
        this.EditBtn.setVisible(false);
        this.ElimBtn.setVisible(false);
        this.CancelBtn.setVisible(false);
        this.CrearBtn.setVisible(true);
        
    }//GEN-LAST:event_ElimBtnActionPerformed
    
    private void EditBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditBtnActionPerformed
        // TODO add your handling code here:
        this.nomTxt.enable(true);
        this.apeTxt.enable(true);
        this.ciTxt.enable(true);
        this.dirTxt.enable(true);
        this.fnacTxt.enable(true);
        this.crgCombo.enable(true);
        this.horCombo.enable(true);
        this.SaveBtn.setVisible(true);
        this.EditBtn.setVisible(false);
        this.ElimBtn.setVisible(false);
        
    }//GEN-LAST:event_EditBtnActionPerformed
    
    private void SaveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveBtnActionPerformed
        // TODO add your handling code here:
        //SaveData();
        this.EditBtn.setVisible(false);
        this.ElimBtn.setVisible(false);
        this.CancelBtn.setVisible(false);
        this.CrearBtn.setVisible(true);
        
    }//GEN-LAST:event_SaveBtnActionPerformed
    
    private void IngBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngBtnActionPerformed
        PushData();
        this.nomTxt.enable(false);
        this.apeTxt.enable(false);
        this.ciTxt.enable(false);
        this.dirTxt.enable(false);
        this.fnacTxt.enable(false);
        this.crgCombo.enable(false);
        this.horCombo.enable(false);
        if(this.CrearBtn.isEnabled()){
            this.CancelBtn.setVisible(false);
        }
        else{
            this.CancelBtn.setVisible(true);
        }
        
    }//GEN-LAST:event_IngBtnActionPerformed
    
    private void CrearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearBtnActionPerformed
        
        this.IngBtn.setVisible(true);
        //this.IngBtn.enable(true);
        this.nomTxt.enable(true);
        this.apeTxt.enable(true);
        this.ciTxt.enable(true);
        this.dirTxt.enable(true);
        this.fnacTxt.enable(true);
        this.crgCombo.enable(true);
        this.horCombo.enable(true);
        this.CrearBtn.setVisible(false);
        this.CancelBtn.setVisible(true);
        this.nomTxt.setText("");
        this.apeTxt.setText("");
        this.ciTxt.setText("");
        this.dirTxt.setText("");
        this.fnacTxt.setText("");
        this.crgCombo.setSelectedIndex(0);
        this.horCombo.setSelectedIndex(0);
    }//GEN-LAST:event_CrearBtnActionPerformed

    private void crgComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crgComboActionPerformed
        // TODO add your handling code here:
        this.crgCombo.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                JComboBox<String> combo = (JComboBox<String>) e.getSource();
                String selectedBook = (String) combo.getSelectedItem();
                
                if(selectedBook.equals("<Editar>")){
                    EditarCargoScn edC = new EditarCargoScn();
                    edC.setVisible(true);
                    
                }
            }
        });
        this.crgCombo.setSelectedIndex(0);
    }//GEN-LAST:event_crgComboActionPerformed

    private void horComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_horComboActionPerformed
        // TODO add your handling code here:
        
        this.horCombo.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                JComboBox<String> combo = (JComboBox<String>) e.getSource();
                String selectedBook = (String) combo.getSelectedItem();
                
                if(selectedBook.equals("<Editar>")){
                    EditarHorarioScn edH = new EditarHorarioScn();
                    edH.setVisible(true);
                }
            }
        });
        this.horCombo.setSelectedIndex(0);
    }//GEN-LAST:event_horComboActionPerformed
    
    public void PushData(){
        try{
            String rpta="";
            if((this.ciTxt.getText().equals(""))||(this.nomTxt.getText().equals(""))||(this.apeTxt.getText().equals(""))||(this.dirTxt.getText().equals(""))||(this.fnacTxt.getText().equals(""))||(this.crgCombo.getSelectedItem().equals("<Editar>"))||(this.horCombo.getSelectedItem().equals("<Editar>"))){
                if(this.ciTxt.getText().equals("")){
                    JOptionPane.showMessageDialog(new JFrame(),"No ha ingresado datos en el campo Cedula/Ruc. Vuelva a intentar","Error",JOptionPane.ERROR_MESSAGE);
                    
                }
                if(this.nomTxt.getText().equals("")){
                    JOptionPane.showMessageDialog(new JFrame(),"No ha ingresado datos en el campo Nombre. Vuelva a intentar","Error",JOptionPane.ERROR_MESSAGE);
                    
                }
                if(this.apeTxt.getText().equals("")){
                    JOptionPane.showMessageDialog(new JFrame(),"No ha ingresado datos en el campo Apellido. Vuelva a intentar","Error",JOptionPane.ERROR_MESSAGE);
                    
                }
                if(this.dirTxt.getText().equals("")){
                    JOptionPane.showMessageDialog(new JFrame(),"No ha ingresado datos en el campo Direccion. Vuelva a intentar","Error",JOptionPane.ERROR_MESSAGE);
                    
                }
                if(this.fnacTxt.getText().equals("")){
                    JOptionPane.showMessageDialog(new JFrame(),"No ha ingresado datos en el campo Fecha de Nacimiento. Vuelva a intentar","Error",JOptionPane.ERROR_MESSAGE);
                    
                }
                if(this.crgCombo.getSelectedItem().equals("<Editar>")){
                    JOptionPane.showMessageDialog(new JFrame(),"No ha selecccionado un cargo. Vuelva a intentar","Error",JOptionPane.ERROR_MESSAGE);
                    
                }
                if(this.horCombo.getSelectedItem().equals("<Editar>")){
                    JOptionPane.showMessageDialog(new JFrame(),"No seleccionado horario. Vuelva a intentar","Error",JOptionPane.ERROR_MESSAGE);
                    
                }
            }
            else{
                rpta = NEmpleado.insertar(this.ciTxt.getText(), this.nomTxt.getText(), this.apeTxt.getText(),this.fnacTxt.getText(),this.dirTxt.getText(),getCargoId(),getHorarioId());
                if (rpta.equals("OK")){
                    JOptionPane.showMessageDialog(new JFrame(),"Ingresado con exito...");
                    nomTxt.setText("");
                    this.apeTxt.setText("");
                    this.ciTxt.setText("");
                    this.dirTxt.setText("");
                    this.fnacTxt.setText("");
                    this.crgCombo.setSelectedIndex(0);
                    this.horCombo.setSelectedIndex(0);
                    this.CrearBtn.setVisible(true);
                    this.IngBtn.setVisible(false);
                    this.nomTxt.enable(true);
                    this.apeTxt.enable(true);
                    this.ciTxt.enable(true);
                    this.dirTxt.enable(true);
                    this.fnacTxt.enable(true);
                    this.crgCombo.enable(true);
                    this.horCombo.enable(true);
                }
                else{
                    JOptionPane.showMessageDialog(new JFrame(),rpta);
                    
                }
                
                
            }
            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(new JFrame(),e.getMessage()+e.getStackTrace());
            
        }
        //GetData();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
        * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
        */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmpleadoScn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmpleadoScn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmpleadoScn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmpleadoScn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmpleadoScn().setVisible(true);
            }
        });
    }
    
    public int getCargoId(){
        ResultSet rs = null;
        DefaultTableModel model=null;
        int id=0;
        try {
            
            id = new NEmpleado().buscar_Cargo_Nombre(this.crgCombo.getSelectedItem().toString());
            if(id!=0){
                return id;
            }
            
            
        } catch (SQLException ex) {
            Logger.getLogger(ProvScn.class.getName()).log(Level.SEVERE, null, ex);
        }
        return 0;
    }
    
    public int getHorarioId(){
        ResultSet rs = null;
        DefaultTableModel model=null;
        int id=0;
        try {
            
            id = new NEmpleado().buscar_Horario_Nombre(this.horCombo.getSelectedItem().toString());
            if(id!=0){
                return id;
            }
            
            
        } catch (SQLException ex) {
            Logger.getLogger(ProvScn.class.getName()).log(Level.SEVERE, null, ex);
        }
        return 0;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelBtn;
    private javax.swing.JButton CrearBtn;
    private javax.swing.JButton EditBtn;
    private javax.swing.JButton ElimBtn;
    private javax.swing.JButton IngBtn;
    private javax.swing.JButton SaveBtn;
    private javax.swing.JTextField apeTxt;
    private javax.swing.JTextField ciTxt;
    private javax.swing.JComboBox crgCombo;
    private javax.swing.JTextField dirTxt;
    private javax.swing.JTable empTbl;
    private javax.swing.JTextField fnacTxt;
    private javax.swing.JComboBox horCombo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nomTxt;
    // End of variables declaration//GEN-END:variables
}
