/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CapaPresentacion;

import CapaNegocios.NReservacion;
import CapaDatos.DReservacion;
import CapaNegocios.NCompras;
import CapaNegocios.NFactura;
import CapaNegocios.NProveedor;
import CapaPresentacion.RsrvScn;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hortencia
 */
public class FactScn extends javax.swing.JFrame {

    /**
     * Creates new form FactScn
     */
    public FactScn() {
        initComponents();
        GetData();
        Calendar cal=Calendar.getInstance();
        String fecha=cal.get(cal.DATE)+"/"+cal.get(cal.MONTH)+"/"+cal.get(cal.YEAR);
        String hora=cal.get(cal.HOUR_OF_DAY)+":"+cal.ge­t(cal.MINUTE)+":"+cal.get(cal.SECOND);
        String cliente = RsrvScn.CltCmb.getSelectedItem().toString();
        String desc = RsrvScn.descTxt.getText();
        double pre = Double.parseDouble(RsrvScn.prcTxt.getText());
        double iva = pre*0.12;
        double tot = pre +iva;
        this.fchTxtFct.setText(fecha);
        this.horTxtFct.setText(hora);
        this.cltTxtFct.setText(cliente);
        this.descTxtFct.setText(desc);
        this.prcTxtFct.setText(String.valueOf(pre));
        this.ivaTxtFact.setText(String.valueOf(iva));
        this.totTxtFct.setText(String.valueOf(tot));
        this.ingBtFct.enable(true);
        this.cancBtFct.enable(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        fchTxtFct = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        horTxtFct = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cltTxtFct = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        descTxtFct = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        prcTxtFct = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        ivaTxtFact = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        totTxtFct = new javax.swing.JLabel();
        ingBtFct = new javax.swing.JButton();
        cancBtFct = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFct = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("factura");
        setPreferredSize(new java.awt.Dimension(600, 480));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/factura.jpg"))); // NOI18N
        jLabel1.setToolTipText("");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 51));
        jLabel2.setText("FACTURA");

        jLabel3.setText("Fecha:");

        fchTxtFct.setText("00/00/0000");

        jLabel4.setText("Hora:");

        horTxtFct.setText("00:00:00");

        jLabel5.setText("Cliente:");

        jLabel6.setText("Descripción:");

        jLabel8.setText("Precio:");

        jLabel10.setText("IVA:");

        jLabel7.setText("Total:");

        ingBtFct.setText("Ingresar");
        ingBtFct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingBtFctActionPerformed(evt);
            }
        });

        cancBtFct.setText("Cancelar");
        cancBtFct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancBtFctActionPerformed(evt);
            }
        });

        tblFct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nº ", "Fecha", "Descripcion", "Precio", "IVA 0", "IVA 12", "Total", "IdEvento"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblFct);
        if (tblFct.getColumnModel().getColumnCount() > 0) {
            tblFct.getColumnModel().getColumn(0).setMinWidth(0);
            tblFct.getColumnModel().getColumn(0).setPreferredWidth(0);
            tblFct.getColumnModel().getColumn(0).setMaxWidth(0);
            tblFct.getColumnModel().getColumn(1).setResizable(false);
            tblFct.getColumnModel().getColumn(2).setMinWidth(0);
            tblFct.getColumnModel().getColumn(2).setPreferredWidth(0);
            tblFct.getColumnModel().getColumn(2).setMaxWidth(0);
            tblFct.getColumnModel().getColumn(3).setResizable(false);
            tblFct.getColumnModel().getColumn(4).setMinWidth(0);
            tblFct.getColumnModel().getColumn(4).setPreferredWidth(0);
            tblFct.getColumnModel().getColumn(4).setMaxWidth(0);
            tblFct.getColumnModel().getColumn(5).setResizable(false);
            tblFct.getColumnModel().getColumn(6).setResizable(false);
            tblFct.getColumnModel().getColumn(7).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(43, 43, 43)
                        .addComponent(fchTxtFct))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cltTxtFct, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(prcTxtFct, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel7))
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(totTxtFct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ivaTxtFact, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(horTxtFct)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cancBtFct)
                    .addComponent(ingBtFct)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(descTxtFct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(127, 127, 127))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(fchTxtFct, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cltTxtFct, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(descTxtFct, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                            .addComponent(prcTxtFct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel10)
                            .addComponent(ivaTxtFact, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(totTxtFct, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(horTxtFct))))
                        .addGap(70, 70, 70)
                        .addComponent(ingBtFct)
                        .addGap(40, 40, 40)
                        .addComponent(cancBtFct)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ingBtFctActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingBtFctActionPerformed
        PushData();
        this.cancBtFct.setVisible(false);
    }//GEN-LAST:event_ingBtFctActionPerformed

    private void cancBtFctActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancBtFctActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_cancBtFctActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FactScn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FactScn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FactScn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FactScn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FactScn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancBtFct;
    private javax.swing.JLabel cltTxtFct;
    private javax.swing.JLabel descTxtFct;
    private javax.swing.JLabel fchTxtFct;
    private javax.swing.JLabel horTxtFct;
    private javax.swing.JButton ingBtFct;
    private javax.swing.JLabel ivaTxtFact;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel prcTxtFct;
    private javax.swing.JTable tblFct;
    private javax.swing.JLabel totTxtFct;
    // End of variables declaration//GEN-END:variables

     public void PushData(){
        try{
            Calendar cal=Calendar.getInstance();
            String fecha=cal.get(cal.DATE)+"/"+cal.get(cal.MONTH)+"/"+cal.get(cal.YEAR);
            String desc = RsrvScn.descTxt.getText();
            double pre = Double.parseDouble(RsrvScn.prcTxt.getText());
            double ivaC = pre*0;
            double ivaD = pre*0.12; 
            double tot = pre +ivaD;
            int idE = 1;
            String rpta="";
            rpta = NFactura.Insertar(fecha,desc,pre,ivaC,ivaD,tot,idE);
                if (rpta.equals("OK")){
                    int d = JOptionPane.showConfirmDialog(null,"Está seguro de ingresar la factura./n Recuerde que las facturas no se pueden anular","Advertencia",JOptionPane.OK_CANCEL_OPTION);
                    if (d==JOptionPane.OK_OPTION){
                        JOptionPane.showMessageDialog(new JFrame(),"Ingresado con exito...");
                        this.setVisible(false);                        
                    }
                else{
                    JOptionPane.showMessageDialog(new JFrame(),rpta);
                    }
                }
        }
        catch(Exception e){
                   JOptionPane.showMessageDialog(new JFrame(),e.getMessage()+e.getStackTrace());
        }
    }
     public void GetData(){
        ResultSet rs = null;
        DefaultTableModel model=null;
        try {
            rs = new NCompras().Mostrar();
            if(this.tblFct.getRowCount()!=0){
                model = (DefaultTableModel)this.tblFct.getModel();
                model.setRowCount(0);
            }
            model = (DefaultTableModel)this.tblFct.getModel();
            while(rs.next()){
                model.addRow( new Object[] {rs.getInt("idFactura"), rs.getString("fecha"), rs.getString("descripcion"), rs.getString("subtotal"), rs.getString("ivaCero"), rs.getString("ivaDoce"), rs.getString("total"), rs.getString("Eventos_idEventos")});
            }
            this.tblFct.setModel(model);
        } catch (SQLException ex) {
            Logger.getLogger(ComprasScn.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
