/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CapaPresentacion;

/**
 *
 * @author jfpal
 */
public class MainScn extends javax.swing.JFrame {

    /**
     * Creates new form MainScn
     */
    public MainScn() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ResBtn = new javax.swing.JButton();
        EvntBtn = new javax.swing.JButton();
        ClieBtn = new javax.swing.JButton();
        CompBtn = new javax.swing.JButton();
        ProvBtn = new javax.swing.JButton();
        EmpBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ResBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icon-reservation.png"))); // NOI18N
        ResBtn.setText("RESERVACIONES");
        ResBtn.setAlignmentY(0.0F);
        ResBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ResBtn.setMaximumSize(new java.awt.Dimension(161, 163));
        ResBtn.setMinimumSize(new java.awt.Dimension(161, 163));
        ResBtn.setPreferredSize(new java.awt.Dimension(161, 163));
        ResBtn.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        ResBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ResBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResBtnActionPerformed(evt);
            }
        });

        EvntBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/calendar-128.png"))); // NOI18N
        EvntBtn.setText("EVENTOS");
        EvntBtn.setAlignmentY(0.0F);
        EvntBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        EvntBtn.setMaximumSize(new java.awt.Dimension(161, 163));
        EvntBtn.setMinimumSize(new java.awt.Dimension(161, 163));
        EvntBtn.setPreferredSize(new java.awt.Dimension(161, 163));
        EvntBtn.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        EvntBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        ClieBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/2901_-_Client_Meetup-128.png"))); // NOI18N
        ClieBtn.setText("CLIENTES");
        ClieBtn.setAlignmentY(0.0F);
        ClieBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ClieBtn.setMaximumSize(new java.awt.Dimension(161, 163));
        ClieBtn.setMinimumSize(new java.awt.Dimension(161, 163));
        ClieBtn.setPreferredSize(new java.awt.Dimension(161, 163));
        ClieBtn.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        ClieBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        CompBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/045-128.png"))); // NOI18N
        CompBtn.setText("COMPRAS");
        CompBtn.setAlignmentY(0.0F);
        CompBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        CompBtn.setMaximumSize(new java.awt.Dimension(161, 163));
        CompBtn.setMinimumSize(new java.awt.Dimension(161, 163));
        CompBtn.setPreferredSize(new java.awt.Dimension(161, 163));
        CompBtn.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        CompBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        ProvBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icon-moving.png"))); // NOI18N
        ProvBtn.setText("PROVEEDORES");
        ProvBtn.setAlignmentY(0.0F);
        ProvBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ProvBtn.setMaximumSize(new java.awt.Dimension(161, 163));
        ProvBtn.setMinimumSize(new java.awt.Dimension(161, 163));
        ProvBtn.setPreferredSize(new java.awt.Dimension(161, 163));
        ProvBtn.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        ProvBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        EmpBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/1027-128.png"))); // NOI18N
        EmpBtn.setText("EMPLEADOS");
        EmpBtn.setAlignmentY(0.0F);
        EmpBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        EmpBtn.setMaximumSize(new java.awt.Dimension(161, 163));
        EmpBtn.setMinimumSize(new java.awt.Dimension(161, 163));
        EmpBtn.setPreferredSize(new java.awt.Dimension(161, 163));
        EmpBtn.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        EmpBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jLabel1.setText("DREAM'S PARK");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ResBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CompBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(88, 88, 88)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EvntBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ProvBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EmpBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ClieBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(326, 326, 326))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(ResBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ClieBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(EvntBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EmpBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(CompBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ProvBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(47, 47, 47))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ResBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ResBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainScn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainScn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainScn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainScn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainScn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ClieBtn;
    private javax.swing.JButton CompBtn;
    private javax.swing.JButton EmpBtn;
    private javax.swing.JButton EvntBtn;
    private javax.swing.JButton ProvBtn;
    private javax.swing.JButton ResBtn;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
